# Generated by Django 3.1.2 on 2020-10-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_image', models.ImageField(upload_to='post_images/')),
                ('post_text', models.CharField(max_length=300)),
                ('post_title', models.CharField(max_length=20)),
                ('post_date', models.DateField(editable=False)),
            ],
        ),
    ]
